### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.AWS.ElasticBeanstalk#2]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by mathieukempe** [comment]
Thanks, I will add comment and other things that are missing ASAP

**Comment by gep13** [comment]
>@mathieukempe said...
Thanks, I will add comment and other things that are missing ASAP

That is great news!  Let us know if you have any questions!

**Comment by augustoproiete** [comment]
Closing as part of the 1.3.3 milestone. Docs are available on the Cake website: https://cakebuild.net/extensions/cake-aws-elasticbeanstalk/
